<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net472</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <PackageReference Include="System.Security.Cryptography.ProtectedData">
      <Version>10.0.0-preview.1.25080.5</Version>
    </PackageReference>
  </ItemGroup>
	
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <Reference Include="System.Security"/>
  </ItemGroup>

</Project>
