<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>TestApp</RootNamespace>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon/>
		<OutputType>WinExe</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<StartupObject/>
		<AssemblyName>TestApp</AssemblyName>
		<NoWarn>
			CA1416; <!-- This call site is reachable on all platforms. -->
		</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<Resource Include="**\*.png"/>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Components\AvalonDock.Themes.VS2010\AvalonDock.Themes.VS2010.csproj"/>
		<ProjectReference Include="..\Components\AvalonDock.Themes.VS2013\AvalonDock.Themes.VS2013.csproj"/>
		<ProjectReference Include="..\Components\AvalonDock\AvalonDock.csproj"/>
	</ItemGroup>
</Project>
